spring:
  datasource:
    data-source-class-name: org.h2.Driver
    url: jdbc:h2:mem:conduit;DB_CLOSE_ON_EXIT=TRUE;MODE=PostgreSQL
    username: sa
    password:
mybatis:
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com:
      pocotech:
        conduit:
          repository: DEBUG
